### ISSUE TITLE
Golang: Duplicate records inserted in database

### ISSUE THREAD

**Issue by kaleshasheik** [kaleshasheik/GoLang#1]
Hi,  I am using below code to insert records into database. I am facing some issue with below code.

Issue is: Records inserted twice.

 But for below stmt, output is 1.  Can someone comment if any issue with below code.
 fmt.Println("Rows Affected:", rowsAffected)

package main

import (  
  "database/sql"
  "fmt"

  _ "github.com/lib/pq"
)

const (  
  host     = "localhost"
  port     = 5432
  user     = "postgres"
  password = "admin"
  dbname   = "Quality"
)

func main() {  
  psqlInfo := fmt.Sprintf("host=%s port=%d user=%s "+
    "password=%s dbname=%s sslmode=disable",
    host, port, user, password, dbname)
  db, err := sql.Open("postgres", psqlInfo)
    
    defer db.Close()

   result, err :=db.Exec("INSERT INTO LOGINS (id,name,password) VALUES($1,$2,$3)",120,"ksh","pwd")
  if err != nil {
    panic(err)
  }
    rowsAffected, _ := result.RowsAffected()

 fmt.Println("Rows Affected is:", rowsAffected)
}

**Comment by tushar-sss** [comment]
Did you get the solution for the same, because I'm facing same.
